### ISSUE TITLE
Convert all error messages used in contracts to custom errors

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#77]
**Description**
Most error messages used in the contracts are string/felt
<img width="586" alt="image" src="https://github.com/user-attachments/assets/c8ac7fb6-61bb-4e09-93c8-b8891d2f5628">

**Action Items**
- Convert all error messages across all contracts to custom errors

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Can I work on this please?I am a blockchain Developer, and my experience includes html, css, react, JavaScript, TypeScript and solidity and Cairo.

### How I plan on tackling this issue
To solve this issue, I'd take the following steps:
1.First, I'll define the custom error types at the beginning of your contract.
2.  Then I'll search for any require(), revert(), or assert() calls where string-based errors are used, and replace them with the custom errors.
3. Next, I'll handle Error Parameters, to make sure error handling is more informative.
4. I'll ensure that all contracts in the system follow the same pattern, that is, if the system contains multiple contracts, I'll define a standard set of custom errors in a shared library and import them across the contracts.
5. Then, after modifying the contracts, I'll ensure that all unit tests are updated to expect the custom errors instead of string errors.

Please assign this issue to me, I'm ready to work.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeib i would love to hop on this issue 

### How I plan on tackling this issue
Convert all error messages in the contracts to use custom errors.
Apply this change across all contracts in the project.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged


I have experience working with Solidity smart contracts, particularly in enhancing error handling by transitioning from string-based errors to custom error types. This expertise will help me efficiently refactor the error messages across contracts, improving gas efficiency and debugging clarity.






### How I plan on tackling this issue
1. **Review Contracts:** Identify all occurrences of string/felt-based error messages across the contracts.
2. **Define Custom Errors:** Create and define custom error types with relevant details to replace the string errors.
3. **Refactor Contracts:** Refactor the error handling code to use the newly defined custom errors.
4. **Test Contracts:** Ensure all contracts still function as expected by running tests after refactoring.
5. **Optimize and Document:** Optimize where necessary and update documentation to reflect the new custom error structure.

**Comment by vijay-kesanakurthi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am fullstack blockchain developer and I have experience in Javascript ,Typescript,React, Go, Rust, Move.

### How I plan on tackling this issue
- Define intent revealing custom error messages.
- Replace all the error messages with the custom error messages across the all contracts.

**Comment by limitlxx** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I've had up to 7 years experience as a full stack developer working with javascript and typescipt. I just started working with Cairo. I believe based on my experience with Data structure and Algorithm, and working with MVC framework I can leverage this knowledge to solve this issue.

### How I plan on tackling this issue
Firstly I will make sure custom errors can enhance readability, maintainability, and error handling. I would approach it by creating custom error classes that extend the built-in Error class. This will allow me to throw specific errors based on the context of my contracts.

**Comment by omsant02** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am Om Santoshwar,
Final year btech UG at IIT Dhanbad,
i have a strong background in web development and blockchain development particularly in Ethereum and Starknet with 3 years of software development experience.

My Technical Skills-
Languages: Typescript, Javascript, Solidity, Rust, Cairo, C++
Frameworks and tools: Scaffold-eth/Stark, Nextjs, MERN, Ethersjs, Hardhat, Foundry, Openzeppelin contracts, Defi, AWS

Experience-
Participated in EthGlobal and other blockchain hackathons
Internships as Blockchain and Fullstack web developer

### How I plan on tackling this issue
i can see, currently the errors are handled using assert and panic in various files,

i have to change all the error handling from assert and panic to custom Error like using 

mod Errors {
    pub const NULL_REWARDS: felt252 = 'Reward amount must be > 0';
    pub const NOT_ENOUGH_REWARDS: felt252 = 'Reward amount must be > balance';
}

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeib i would love to work on this
this issue is easy to tackle

### How I plan on tackling this issue
Identify All Error Messages:

Locate all string/felt error messages used in the contracts.
Convert to Custom Errors:

Replace each identified error message with a corresponding custom error.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello @princeibs I'm a frontend and a blockchain developer and this is something i can work on ASAP. I did love to be assigned. ETA: 24HRS

### How I plan on tackling this issue
here is how i intend to approve and solve this:
- will check all the functions understanding what the do 
- I will check and understand the error messages 
- I will then create and convert all error messages into custom errors
