### ISSUE TITLE
Fix problem with commitlint workflow file

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#79]
**Description**
[Commit lint workflow file](https://github.com/sivicstudio/starkludo/blob/dev/.github/workflows/commitlint.yml) currently has some problems preventing it from running successfully

**Action Items**
- Debug the commit lint workflow file
- Fix problem preventing it from running successfully
- _Check out the [commitlint docs](url) for help_

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello , i am a frontend and blockchain developer , with a strong background in Next.js, Typescript,Javascript,React,and cario.and i am exicted to contribute my skills to this project . i am avaliable to work . please assign me

### How I plan on tackling this issue
I will approach the problem by doing the following:

1.Firstly reviewing the commit lint workflow file for syntax errors or misconfigurations.
2.Next is to check the commitlint documentation for guidance on proper setup: https://commitlint.js.org.
3. Then ensure the workflow is using the correct version of commitlint.
4. Also i will debug by running the workflow locally or in a test branch.
5.  Also i wll fix any issues found, such as incorrect paths or misused configuration options.
6.  Finally i will test the workflow to verify it runs successfully after the fix.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged


I have experience with CI/CD pipelines, GitHub workflows, and linting tools like CommitLint. I am proficient in debugging workflow files and ensuring smooth integration within projects, which will help resolve this issue quickly.





### How I plan on tackling this issue

1. **Examine the Workflow File:** Review the existing commit lint workflow for any syntax or configuration issues.
2. **Check Logs:** Analyze the error logs from the failed workflow runs to identify the root cause.
3. **Refer to CommitLint Docs:** Use the official CommitLint documentation to validate the setup and ensure best practices are followed.
4. **Fix the Issues:** Correct any errors or misconfigurations in the workflow.
5. **Test the Workflow:** Run the workflow after the fix to confirm it executes successfully without errors

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
"I have experience debugging and optimizing CI/CD workflows, including troubleshooting commit lint issues

### How I plan on tackling this issue
I would start by reviewing the commit lint workflow file to identify errors or misconfigurations. Next, I'd analyze the logs from the failed workflow runs to pinpoint the issue. Using the Commitlint documentation, I'd verify configurations and adjust as necessary, then test the workflow to ensure it runs successfully

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
Review the Current Workflow File: Start by reviewing the existing commit lint workflow file (e.g., .github/workflows/commit-lint.yml) to identify any obvious issues like syntax errors, incorrect paths, or misconfigurations.

Check Workflow Logs:

    Run the workflow manually if possible, or check the existing workflow logs in the GitHub Actions tab.
    Look for specific error messages or warnings in the logs that can give clues about what’s failing.

Verify the Commit Lint Configuration: Ensure that the workflow file is using the correct version and configuration for commit lint. It should match the format and requirements specified in the CommitLint documentation.

Common Issues to Look For:

    Missing Dependencies: Make sure the @commitlint/cli and @commitlint/config-conventional are installed and configured correctly in the project.
    Node.js Version: Ensure the workflow runs on a compatible version of Node.js.
    Incorrect Paths: Verify that the correct paths for config files like commitlint.config.js are set in the workflow.

Modify the Workflow File
Verify Commit Lint Configuration (commitlint.config.js): Ensure the commitlint.config.js file is correctly set up in the root of the project. 

Test

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello @princeibs I'm a frontend and a blockchain developer and this is something i can work on ASAP. I did love to be assigned. ETA: 24HRS

### How I plan on tackling this issue
How I plan to approach and get it done:
- I will investigate the commitlint workflow file to identify the issues preventing it from running.
- After debugging, I will fix the problems causing the workflow failure.
Looking forward to contribute

**Comment by Abeeujah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a Systems Software Engineer, with extensive knowledge in systems programming languages such as Rust, GoLang, C and Zig. I have experience with writing and debugging MakeFiles, DockerFiles, YAML and JSON scripts / config files.

### How I plan on tackling this issue
The problem is a User Permissions problem, and I plan to approach it by using the least responsibility privilege, to ensure that the process runs with only those privileges required by the task.
