### ISSUE TITLE
Create the "Invite player" function

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#83]
**Description**
- The invite player function should be added to game actions
- The function should allow the creator of a game invite other player into the game using the player username
 - It should take in the game Id and the player username and invite the player to the game
 - Only the game creator can invite players to join that particular game
 - The invited player will need to accept the invitation to be fully part of the game

**Action Items**
- Create the invite player function
- Create the corresponding test cases for the invite player function

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a blockchain developer , and i have experience in html, react , css, javascript , typescript, cario and solidity.

### How I plan on tackling this issue
To implement the invite player function, I would carry out the following:

Define a function invitePlayer(gameId, username) that authenticates the game creator, validates inputs, checks game existence and capacity, and verifies the player's existence and non-duplication.

Within the function, send an invitation to the player via notification or email and update the game state to reflect the pending invitation.

Implement this logic using your chosen programming language and game development framework, such as Node.js and MongoDB.

Create comprehensive test cases to ensure successful invitations, invalid game IDs, invalid usernames, and other scenarios.

Finally, integrate the invite player function with your game's action system, ensuring only authorized game creators can invite players.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeib please can i work on this issue 

### How I plan on tackling this issue
Steps to Implement the Invite Player Function
Define the invitePlayer Function:

Parameters: gameId, playerUsername.
Check Permissions:

Verify that the user is the game creator.
Send Invitation:

If authorized, send an invitation to playerUsername and mark it as pending.
Player Acceptance:

Implement functionality for the invited player to accept the invitation.
Create Test Cases:

Ensure:
Only the creator can invite players.
Invitations are sent correctly.
Invited players can accept.
Proper error handling for unauthorized access.
Testing:

Run test cases to confirm functionality.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @prince can i hop on this issue

### How I plan on tackling this issue
Invite Player Function:

Check if the game exists by gameId.
Ensure the current user is the game creator.
Verify if the player exists by playerUsername.
Ensure the player is not already invited or part of the game.
Add the player to the invitedPlayers array and save the game.
Test Cases:

Game not found: Ensure the function throws an error if the game doesn't exist.
Unauthorized user: Verify that only the game creator can invite players.
Player already in game: Check that the function throws an error if the player is already in the game or invited.
Successful invitation: Confirm the function invites the player if all conditions are met.

**Comment by akintewe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Having studied computer science, with almost 5 years of work experience I have a lot of expertise with TypeScript and Cairo, which gives me a solid basis in frontend integration and smart contract development. My experience with these technologies enables me to effectively handle any essential off-chain components as well as the on-chain logic needed for the invite player function.

### How I plan on tackling this issue
I would first look at the current game structure to figure out the best integration point for the invite process before implementing the "Invite player" function. Comprehending the current player management system and game state representation is necessary for this. Next, I would create the invite_player function, which would add the invited player to an invitation list for that particular game, confirm the caller's legitimacy as the game producer, and check their eligibility. I would schedule the logic for accepting invitations and the events required for monitoring them concurrently. Frontend integration would be taken into consideration to offer a smooth user experience, and testing would cover a range of scenarios to guarantee robustness. I would keep thorough records all along the way to make maintenance easier in the future and to help users.

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hi, I’m Jose Mario from Costa Rica. With over 15 years of full-stack development experience, I am actively involved with Dojo Coding and am currently expanding my expertise in Rust, Cairo, and Solidity.

### How I plan on tackling this issue
**Create the "invite_player" function** in the `game_actions.cairo`
- Add a function `invite_player` that takes in `game_id` and `player_username`.
- Ensure only the game creator can invite players by checking the caller's address against the `game.creator`.
- Use a mapping (`invitations_map`) to store and check whether a player has already been invited.
- If the player has not been invited, mark them as invited.

**Implement the invite_player function logic**
- Retrieve the caller's address using `get_caller_address()`.
- Read the game from `games_map` to check the creator's address.
- Check if the player has already been invited using `invitations_map`.
- Write to `invitations_map` to mark the player as invited if all checks pass.

**Tests**
- Ensure the game creator can successfully invite a player.
- Verify that non-creators cannot invite players.
- Ensure the function prevents re-inviting the same player.

**Comment by jocelynmh** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have experience in software development and have worked with applications based on object-oriented programming. I have trained at DOJO CODING, where I have practiced the Cairo and TypeScript languages. This has allowed me to understand the importance of user roles in games, differentiating between creators and players. Additionally, I have skills in writing and executing test cases to ensure that the functionalities are robust and error-free.

### How I plan on tackling this issue
To tackle the issue of implementing the "invite player" function, I’d start by really understanding what’s needed. It’s crucial that only the game creator can send out invitations, so that has to be clear from the get-go.

Next, I’d design the invitePlayer(gameId, username) function. This function would need to check that the person trying to send the invite is indeed the game creator. It should also verify whether the username provided is valid and if the player exists in our database. Once everything checks out, the function would send the invitation and update the game state to reflect that an invitation has been sent—whether it's pending, accepted, or declined.

When it comes to implementation, I’d use appropriate data structures to manage the relationships between games and players, making sure to handle any unexpected situations, like trying to invite someone who’s already in the game or who doesn’t exist.

I’d also think about the user interface. I want it to be easy for the game creator to send invites, so I’d design a simple screen where they can enter the player’s username and send the invite, displaying clear success or error messages.

I wouldn’t forget about testing, either. It’s essential to ensure the function works correctly, so I’d write several tests to cover different scenarios: when an invite is successfully sent, when a user tries to invite without permission, and when the invited player doesn’t exist.

Finally, I’d document everything so that any other developer can understand how the function works and what it does.

With this approach, I can make sure that the "invite player" function is effective and integrates smoothly into the game.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
I will:

    Add the invitePlayer(gameId, playerUsername) function to the game actions.
    Ensure only the game creator can invite players by checking the creator’s ID.
    Implement logic for the invited player to accept the invitation.
    Write test cases to cover successful invites, invalid invites (non-creator attempts), and player invitation acceptance.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello @princeibs I'm a front-end and a blockchain developer. I will love to work on this 

### How I plan on tackling this issue
Below are steps on how I intend to get this solved:
- I will add an "invitePlayer" function to the game actions
- I will accept gameId and playerUsername as parameters
- I will ensure only the game creator can invoke this function by checking the creator's ID
- I will verify that the game ID exists
- I will ensure the player has not already joined or been invited
- I will add the player’s username to a list of invited players.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have worked extensively on designing functions to manage user roles, permissions, and interactions. This involved building secure mechanisms for access control, ensuring only authorized users could execute specific actions—similar to the requirements of this task. I plan to diversify my expertise and this issue seems fit to me, and I am well-equipped to develop this feature with precision and ensure robust handling of user interactions.

### How I plan on tackling this issue
I plan on to develop the invite player function to ensure only the game creator can send invitations by verifying the game ID and player username, implement logic for the invited player to accept or decline, and create comprehensive test cases to validate functionality, including scenarios for invitation handling and user authorization.
