### ISSUE TITLE
Add images of players profiles next to board

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#88]
**Description**
![image](https://github.com/user-attachments/assets/06ef9f37-952d-4bd6-b80b-028f653eed24)
Each player in StarkLudo has a username and a profile image. There is also an indication of which player should play next. But this has not been implemented yet. 

The profile image of each player is expected to be displayed next to the player's position on the board. Currently, the profile image of the player are not displayed next to their various positions on the board.

**Action Items**
- Update the board layout to display each player's profile image next to their position on the board
- There should also be an indication of which player is rolling the dice next (as in seen in the top left player from the design)
- The position of the player's profile picture should remain fixed even when the board is changed
- You can use dummy images as profile images of the players for now

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Can I please be assigned to this issue ? I am a frontend and blockchain developer with background in Html, css, cario, solidity, javascript , typescript etc. i hope this issue is assigned to me i am ready to work to achieve what is required .

### How I plan on tackling this issue
1. Update Board Layout: Add anImage component next to each player's position on the board using absolute positioning to ensure it remains fixed.  
2. Indicate Active Player: Highlight the active player (who rolls next) by applying a visual indicator, like a border or background change around their profile image.
3. Maintain Player Position: Ensure the profile images are positioned relative to the board and don’t move when the board updates.
4. Dummy Images: Use placeholder images until real profile pictures are available.

**Comment by MPSxDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello, I am Manuel, a process engineer and web3 developer. I have participated in Starknet Bootcamps, ETHGlobal  and am an Elite winner of Speedrunstark. I have a high capacity to solve problems. I am a member of the DojoCoding community.
I hope this issue is assigned to me. I am available to work immediately to achieve what is required in the shortest time possible.

### How I plan on tackling this issue
1. **Update the board layout:**
   - Modify the board to display each player's profile image next to their position.

2. **Indicate the next player:**
   - Add a visual indicator to show which player is rolling the dice next (based on the design in the top left corner).

3. **Keep profile images fixed:**
   - Ensure that the player's profile picture stays in its position, even if the board layout changes.

4. **Use dummy images:**
   - Use placeholder images for the players' profiles for now.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeibs i would love to take on this issue

### How I plan on tackling this issue
Task Overview:

Add player profile images next to their positions on the StarkLudo board.
Indicate which player is rolling the dice next.

**Comment by TEMHITHORPHE** [comment]
@princeibs When you say "remain fixed", you mean "wrt the board" right ? behaves like it's positioned "absolute" to the board ?

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeibs i'm a frontend developer kindly assign

### How I plan on tackling this issue
Update the board layout:

Modify the board to display each player's profile image next to their position.
Indicate the next player:

Add a visual indicator to show which player is rolling the dice next (based on the design in the top left corner).
Keep profile images fixed:

Ensure that the player's profile picture stays in its position, even if the board layout changes.
Use dummy images:

Use placeholder images for the players' profiles for now.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
I will update the board layout to display each player's profile image next to their position on the board by adjusting the design to include placeholders for profile images. I will ensure that each player's profile image remains fixed to their respective positions, even when the board changes. For the indication of which player will roll the dice next, I will add a visual marker that highlights the top left player, as per the design. Dummy images will be used temporarily for the players' profile pictures to ensure the layout and functionality are properly implemented.

**Comment by Solomonsolomonsolomon** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Fullstack developer and lead on an onlydust project

### How I plan on tackling this issue
As there is already a board layout,I will update the existing layout to be able to include images as seen in the UI above,I will also ensure to apply the visual indicator to keep track of turns as shown above

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
With experience in game UI development, especially handling player avatars and indicators, I can effectively update the board to display each player's profile image next to their position and ensure it remains fixed during gameplay changes.

### How I plan on tackling this issue

I would begin by updating the board layout to include space for each player's profile image next to their position. Then, I would implement logic to ensure the profile image remains fixed, even when the board changes. Additionally, I would add an indicator to show which player is currently rolling the dice. Finally, I would test the functionality using dummy images to ensure everything works correctly before deploying the final solution.
