### ISSUE TITLE
Implement design for Wallet selection 

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#90]
**Description**
New design for Wallet selection:
![image](https://github.com/user-attachments/assets/dc1b340c-fe9b-4c87-be2d-56abd5936a00)

**Action Items**
- Replace the current wallet selection UI with the new design
- Also update the "Disconnect" button UI to a standard button. Here is an example of a standard button: 
![image](https://github.com/user-attachments/assets/3972528b-bf48-4fbc-9abe-fe9b30842533)

**Comment by Oshioke-Salaki** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Please can I do this? My name is oshioke salaki and i am a front end developer and web3 developer

### How I plan on tackling this issue
I would solve this by carefully studying the style guide used for buttons and update the connect page and its buttons. i would implement the connect page to be pixel perfect.

**Comment by coxmars** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm developing an on-chain game called Bytebeasts with Unity/Dojo so I have experience in this field and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc.

### How I plan on tackling this issue
- Review the provided design and understand its structure (wallet selection, buttons, etc.).
- Update the current wallet selection UI to match the new design, ensuring consistency with existing styles. Standardize the "Disconnect" button using a pre-existing component.
- Test the new UI to ensure functionality and visual consistency.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello, i am Dprof-in-tech, an experienced Full Stack Blockchain Developer and  I am excited to contribute my skills to this project in this ODHACK 8. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js,  Rust and Cairo, I've honed my technical skills across the blockchain development landscape.
My journey with OnlyDust began at Edition 2, and I've since made 34 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.
My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we begin ODHACK 8, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.
Below is a link to my OnlyDust public profile.
https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
to solve this issue i would work iwth the given ui and rebuild the connect walet interface. also update the disonnect button uI to a standard button as requested.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeibs my name is martin please can i take on this issue 
i'm a frontend developer and a blockchain dev

### How I plan on tackling this issue
Task Overview:

Replace the current wallet selection UI with a new design.
Update the "Disconnect" button to match a standard button style.

Please kindly assign :)

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello, my name is Ugo-X and I am a full stack Dev.

### How I plan on tackling this issue


I will Check out the new design, rebuild the wallet selector UI, and fix up that "Disconnect" button to match our usual button style.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @prineibs my name is justice i'm a frontend dev and this would be my first time contributing on the ecosystem please assign me 

### How I plan on tackling this issue
I would solve this by studying the style used for buttons and update the connect page and its buttons. i would make this pixel perfect and responsive 

please assign

**Comment by Kingsuite** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have a solid foundation in frontend development, with experience in JavaScript, HTML, CSS, and frameworks like React. My background includes working on user interface (UI) designs, which has equipped me with the skills to create intuitive and visually appealing layouts

### How I plan on tackling this issue
Replace Wallet Selection UI: I would begin by designing the new wallet selection interface, ensuring it adheres to modern UI principles for improved user experience. This involves updating the layout, colors, and interaction elements to create a more visually appealing interface.

Standardize the Disconnect Button: Next, I would replace the existing disconnect button with a standard button style, making sure it aligns with the overall design language of the application. This includes updating its size, shape, color, and any accompanying text to ensure it’s intuitive for users.

Test Functionality: Finally, I would thoroughly test both the wallet selection and disconnect functionalities to ensure they work seamlessly and provide a smooth user experience after the changes.
