### ISSUE TITLE
Player should not be able to roll dice after reaching home

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#93]
**Description**
Currently, after a player reaches home, the player is still able to roll the dice.
This is not the expected behaviour. A player is not supposed to be able to roll the dice once the player reaches home

**Action items**
- Fix bug that allows player to roll dice after reaching home

**Comment by Naomi-Gift** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a web3/frontend developer

### How I plan on tackling this issue
To fix this bug, implement a condition that checks if the player has reached home before allowing a dice roll. If the player is at home, disable or bypass the dice roll functionality. Ensure the game logic is updated to prevent dice interaction for that player once they reach home.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend and blockchain developer with background in Html, css, cario, solidity, javascript , typescript etc. i hope this issue is assigned to me i am ready to work to achieve what is required .

### How I plan on tackling this issue
1. Condition check: Introduce a condition that checks if the player has reached home before allowing the dice to roll.
2. Disable dice roll: Once the player reaches home, disable the dice roll functionality for that player.
3. Update game state: Ensure that the player's state is updated when they reach home, marking them as "finished" or "home" so that the roll function knows not to proceed for that player.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

 ### My background and how it can be leveraged
I have a background in software development with experience in JavaScript, TypeScript, React, HTML, CSS, and Python. As an intermediate frontend developer, I have worked on various projects, including UI design, API integration, and game development

 ### How I plan on tackling this issue
 Identify Player's State (Reaching Home): Ensure the program  tracks whether the player has reached home. Using a flag  indicating this state.  i will add a boolean property like hasReachedHome to the player's object or state.

 Disable Dice Roll When Player is Home: In the function responsible for rolling the dice (e.g., rollDice()), i will add a check that prevents the player from rolling if they have already reached home.

**Comment by vijay-kesanakurthi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am fullstack blockchain developer and I have experience in Javascript ,Typescript,React, Go, Rust, Move.

### How I plan on tackling this issue
- Use the existing winners array to track players who have reached home.
- Update the `moveValidator` function to skip players who have reached home.
- Modify the Dice component to disable the roll button for players who have reached home.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeibs  please let me work on this issue 

### How I plan on tackling this issue
Track Player State: Ensure the player's status is accurately recorded.
Update Logic: Modify the dice rolling functionality to disable rolling if the player is home.
User Feedback: Provide visual cues (e.g., disable roll button) to indicate inability to roll.
Testing: Verify the fix and ensure other game functions remain unaffected.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hey @princeibs i'm martin by name and i would love to take on this issue :)

### How I plan on tackling this issue
- Identify Condition:

Determine the current logic that allows dice rolling after reaching home.
- Implement Fix:

Modify the game logic to prevent dice rolling once a player has reached home.
- Test Changes:

Ensure that the bug is resolved and that players cannot roll the dice after reaching home.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
I will address the bug that allows the player to roll the dice after reaching home by first identifying the player's state when they reach home. Then, I will implement a condition that prevents the player from rolling the dice once they've completed their journey. Additionally, I will ensure that any UI elements related to rolling the dice are disabled or hidden for that player. Finally, I will thoroughly test the fix to confirm that the player can no longer roll the dice once they've reached home.

**Comment by Solomonsolomonsolomon** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
3+ YEARS FULLSTACK DEVELOPER 

### How I plan on tackling this issue
Look through current impl to determine why player can still roll dice after reaching home,fix the identified issue

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
With a strong background in game development and logic handling, I have experience in ensuring correct gameplay mechanics and state transitions. I can effectively resolve the issue by refining the game logic to prevent dice rolls once a player reaches home, ensuring a smooth and accurate game experience.

### How I plan on tackling this issue
I  would begin by reviewing the current game logic, specifically focusing on the conditions that allow dice rolls. Next, I would implement a check to ensure that once a player reaches home, they are no longer permitted to roll the dice. This would involve updating the game state to reflect that the player has completed their turn upon reaching home. Finally, I would conduct thorough testing to verify that the bug is resolved and the new logic works correctly without impacting other game functions.

this will be my entrypoint to contributing in ODhack :)

**Comment by ibsule** [comment]
Closed by #103
